# Generated by Django 5.0.6 on 2024-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exceldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('yearfounded', models.IntegerField()),
                ('industy', models.CharField(max_length=200)),
                ('sizerange', models.IntegerField()),
                ('locality', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('linkedinurl', models.CharField(max_length=200)),
                ('currentemployee', models.IntegerField()),
                ('totalemployee', models.IntegerField()),
            ],
            options={
                'db_table': 'exceldata',
            },
        ),
    ]
