# Generated by Django 5.0.6 on 2024-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_exceldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='sizerange',
            field=models.CharField(max_length=10),
        ),
    ]
